FROM ruby:2.3.4-alpine
MAINTAINER Ben Titcomb <btitcomb@scpr.org>

RUN apk update && apk add --no-cache \
  make \
  gcc \
  libgcc \
  g++ \
  libc-dev \
  libffi-dev \
  imagemagick \
  exiftool \
  git \
  mysql-dev \
  ruby-json \
  yaml \
  zlib-dev \
  libxml2-dev \
  libxslt-dev \
  tzdata \
  yaml-dev \
  python2 \
  caddy \
  openrc \
  nodejs

RUN addgroup -S assethost && adduser -S -g assethost assethost

ENV HOME /home/assethost

WORKDIR $HOME

EXPOSE 2015

