FROM ruby:2.3.4-alpine
MAINTAINER Ben Titcomb <btitcomb@scpr.org>

RUN apk update && apk add --no-cache \
  make \
  gcc \
  libgcc \
  g++ \
  libc-dev \
  libffi-dev \
  imagemagick \
  exiftool \
  git \
  mysql-dev \
  ruby-json \
  yaml \
  zlib-dev \
  libxml2-dev \
  libxslt-dev \
  tzdata \
  yaml-dev \
  nginx \
  openrc \
  nodejs

ENV HOME /home/assethost

WORKDIR $HOME

ENV PATH="${HOME}/bin:${PATH}"

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

CMD server

